# Generated by Django 6.0.3 on 2026-03-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizador', '0002_remove_evento_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('catering', 'Catering'), ('logistica', 'Logistica'), ('espacio', 'Espacio'), ('marketing', 'Marketing'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proveedor', models.CharField(blank=True, max_length=150)),
                ('fecha_gasto', models.DateField()),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='organizador.evento')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha_gasto', 'concepto'],
            },
        ),
    ]
