# Generated by Django 6.0.3 on 2026-03-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='perfilorganizador',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='perfilorganizador',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='perfilorganizador',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='perfilorganizador',
            name='sitio_web',
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='perfilorganizador',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
