# Generated by Django 6.0.3 on 2026-03-25 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('canal_envio', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('link', 'Link')], default='email', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('abierta', 'Abierta'), ('vencida', 'Vencida')], default='pendiente', max_length=15)),
                ('codigo_acceso', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('mensaje_personalizado', models.TextField(blank=True)),
                ('invitado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitacion', to='invitados.invitado')),
            ],
            options={
                'verbose_name': 'Invitación',
                'verbose_name_plural': 'Invitaciones',
            },
        ),
    ]
