# Generated by Django 6.0.3 on 2026-03-26 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invitaciones', '0001_initial'),
        ('invitados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('interna', 'Interna')], default='email', max_length=20)),
                ('asunto', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('entregada', 'Entregada'), ('leida', 'Leida'), ('fallida', 'Fallida')], default='pendiente', max_length=15)),
                ('fecha_programada', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('invitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='invitaciones.invitacion')),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='invitados.invitado')),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_programada', '-id'],
            },
        ),
    ]
