# Generated by Django 6.0.3 on 2026-03-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-id'], 'verbose_name': 'Notificacion', 'verbose_name_plural': 'Notificaciones'},
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='fecha_programada',
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='canal',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=20),
        ),
    ]
